---
- name: Disable SSH password authentication 
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^(PasswordAuthentication yes)$'
    line: 'PasswordAuthentication no'

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"
    use: systemd

- name: Update and upgrade apt packages
  apt:
    upgrade: 'yes'
    update_cache: yes

- name: Load br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Let iptables see bridged ip traffic
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'

- name: Let iptables see bridged ip6 traffic
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'

- name: Install iptables legacy packages
  apt:
    pkg:
      - iptables
      - arptables
      - ebtables

- name: Update iptables alternative
  alternatives:
    name: iptables
    path: /usr/sbin/iptables-legacy

- name: Update ip6tables alternative
  alternatives:
    name: ip6tables
    path: /usr/sbin/ip6tables-legacy

- name: Update arptables alternative
  alternatives:
    name: arptables
    path: /usr/sbin/arptables-legacy

- name: Update ebtables alternative
  alternatives:
    name: ebtables
    path:  /usr/sbin/ebtables-legacy

- name: Install packages for repositories over HTTPS
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
    update_cache: yes

- name: Enable cgroups
  lineinfile:
    path: /boot/firmware/nobtcmd.txt
    regex: '(.*fixrtc)$'
    backrefs: true
    line: '\1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1'
  notify: Reboot system

# Run all pending handlers instead of waiting, i.e reboot host now.
- meta: flush_handlers

