---
masters:
  hosts:
    master.1:
      ansible_host: 192.168.1.40
      ansible_user: ubuntu
      ansible_python_interpreter: /usr/bin/python3.7

workers:
  hosts:
    worker.1:
      ansible_host: 192.168.1.41
      ansible_user: ubuntu 
      ansible_python_interpreter: /usr/bin/python3.7
    worker.2:
      ansible_host: 192.168.1.42
      ansible_user: ubuntu 
      ansible_python_interpreter: /usr/bin/python3.7
